### ISSUE TITLE
Improve error message for posix_spawn failure in PlatformBuilder.kt

### ISSUE THREAD

**Issue by tokuhirom** [05nelsonm/kmp-process#104]
The current implementation at [PlatformBuilder.kt:165](https://github.com/05nelsonm/kmp-process/blob/26acb3eab31a85aedc26a2b1613c9d177e539d9c/library/process/src/unixMain/kotlin/io/matthewnelson/kmp/process/internal/PlatformBuilder.kt#L165) shows the error message "io.matthewnelson.kmp.file.IOException: posix_spawn failure in pre-exec/exec step. Bad arguments?" on error. This message is not very informative and makes it difficult to debug the issue.

I suggest enhancing the error message by using `strerror` to get the specific error information when an error occurs. This will provide more detailed information about the cause of the error, making it easier to identify and fix the problem.

**Proposed Change:**
Update the error handling to include `strerror` for more informative error messages. For example:

```kotlin
val errorMessage = strerror(posix_errno)
throw IOException("posix_spawn failure in pre-exec/exec step: $errorMessage")
```

This change will help developers better understand the nature of the error and take appropriate action to resolve it.

Thank you for considering this improvement.

**Comment by 05nelsonm** [comment]
`posix_spawn` errno is already checked via the `.check` extension function.

There are 2 stages to how the system executes `posix_spawn`, the first of which returns an immediate error and sets `errno`. If there is a failure after that (indicative of `pid` being `-1`), there is no way to determine what that error was attributed to, thus the message of "Bad arguments?".

Looking at the code though, I do see an issue that could be improved upon which I.all open a separate issue ticket for.

What was the command and arguments you were running, and what platform?
