### ISSUE TITLE
Allow starting a detached process In JS

### ISSUE THREAD

**Issue by ingokegel** [05nelsonm/kmp-process#129]
I am starting a GUI application that should not terminate when the node.js host environment exits.

This should be possible by making the value of

    opts["detached"] = false

configurable in library/process/src/jsMain/kotlin/io/matthewnelson/kmp/process/internal/PlatformBuilder.kt. 

Probably unref() would have to be called on the child process immediately in detached mode.

**Comment by 05nelsonm** [comment]
I'll have to look into Node's API docs, but I think the underlying streams and some other things would need to be `unref`'d as well? Also, do you know how would I write a unit test to ensure that the host environment does not hang when it exits (i.e. `kmp-process` called `unref` on all of the necessary things)?

**Comment by ingokegel** [comment]
> the underlying streams and some other things would need to be unref'd as well? 

No, just calling` child.unref();` should be enough.

>how would I write a unit test to ensure that the host environment does not hang when it exits

I would say that a unit test starting a detached process tests this implicitly because the host environment of the unit test must exit. If, for some reason, the host environment was hanging on the child process, the test would not complete and would eventually time out.

**Comment by 05nelsonm** [comment]
I've published a `-SNAPSHOT` for #132 with this functionality added.

Could you please try it out and lemme know? I will merge to master and publish `0.1.2` afterwards.

```kotlin
repositories {
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
}
```

```kotlin
dependencies {
    implementation("io.matthewnelson.kmp-process:process:0.1.2-SNAPSHOT")
}
```

**Comment by ingokegel** [comment]
Thank you so much! I have tested it with my VS Code extension and multiple windows where each window has its own node environment, and it works as expected.

**Comment by 05nelsonm** [comment]
Version `0.1.2` is available now with the added functionality.
